// src/commands/InitCmd.cpp
//
// batbox::commands::InitCmd — implements the /init slash command.
//
// Behaviour:
//   1. Checks ctx.cwd for project markers (package.json, Cargo.toml,
//      CMakeLists.txt, pyproject.toml, go.mod, build.gradle, Makefile,
//      README variants).  Refuses with Err when none are found.
//   2. Scans the top two directory levels for file names (no contents read).
//   3. Derives a brief stack summary from detected markers.
//   4. Writes (or overwrites with user confirmation) BATBOX.md in ctx.cwd.
//
// No aliases.
//
// Registration entry point:
//   void register_init_cmd(SlashCommandRegistry&);

#include <batbox/commands/ISlashCommand.hpp>
#include <batbox/commands/SlashCommandRegistry.hpp>
#include <batbox/core/Result.hpp>
#include <batbox/repl/CommandContext.hpp>

#include <algorithm>
#include <array>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;

namespace batbox::commands {

// ---------------------------------------------------------------------------
// Project marker filenames
// ---------------------------------------------------------------------------

static constexpr std::array<std::string_view, 10> kMarkers = {
    "package.json",
    "Cargo.toml",
    "CMakeLists.txt",
    "pyproject.toml",
    "go.mod",
    "build.gradle",
    "Makefile",
    "README.md",
    "README.txt",
    "README",
};

// ---------------------------------------------------------------------------
// Stack detection
// ---------------------------------------------------------------------------

static std::string detect_stack(const fs::path& root) {
    std::vector<std::string> parts;

    auto has = [&](std::string_view name) -> bool {
        return fs::exists(root / name);
    };

    if (has("package.json"))   parts.push_back("Node.js");
    if (has("Cargo.toml"))     parts.push_back("Rust");
    if (has("CMakeLists.txt")) parts.push_back("C++ / CMake");
    if (has("pyproject.toml")) parts.push_back("Python");
    if (has("go.mod"))         parts.push_back("Go");
    if (has("build.gradle"))   parts.push_back("JVM / Gradle");
    if (has("Makefile") && parts.empty()) parts.push_back("Make-based");

    if (parts.empty()) return "Unknown stack";

    std::string result;
    for (std::size_t i = 0; i < parts.size(); ++i) {
        if (i > 0) result += ", ";
        result += parts[i];
    }
    return result;
}

// ---------------------------------------------------------------------------
// File-tree scan (top two levels, names only)
// ---------------------------------------------------------------------------

static std::string scan_tree(const fs::path& root) {
    std::vector<std::string> entries;

    std::error_code ec;
    for (const auto& entry : fs::directory_iterator(root, ec)) {
        if (ec) break;
        const std::string name = entry.path().filename().string();
        if (name.empty() || name[0] == '.') continue;
        if (name == "node_modules" || name == "target" ||
            name == "build"        || name == "__pycache__") continue;

        entries.push_back(name);

        if (entry.is_directory()) {
            std::error_code ec2;
            for (const auto& sub : fs::directory_iterator(entry.path(), ec2)) {
                if (ec2) break;
                const std::string sname = sub.path().filename().string();
                if (sname.empty() || sname[0] == '.') continue;
                entries.push_back("  " + name + "/" + sname);
            }
        }
    }

    std::sort(entries.begin(), entries.end());

    std::ostringstream oss;
    for (const auto& e : entries) {
        oss << "  " << e << '\n';
    }
    return oss.str();
}

// ---------------------------------------------------------------------------
// BATBOX.md template generator
// ---------------------------------------------------------------------------

static std::string make_batbox_md(const fs::path& root,
                                   const std::string& stack,
                                   const std::string& tree)
{
    std::ostringstream md;
    md << "# BATBOX.md — Project Memory\n\n";
    md << "Generated by batbox `/init`. Edit freely — batbox reads this file on startup\n";
    md << "to understand your project context.\n\n";
    md << "## Project\n\n";
    md << "**Root**: " << root.string() << "\n";
    md << "**Stack**: " << stack << "\n\n";
    md << "## File tree (top 2 levels)\n\n";
    md << "```\n";
    md << tree;
    md << "```\n\n";
    md << "## Notes\n\n";
    md << "<!-- Add project-specific notes here. batbox will include this context\n";
    md << "     in the system prompt for every conversation in this directory. -->\n";
    return md.str();
}

// ---------------------------------------------------------------------------
// InitCmd
// ---------------------------------------------------------------------------

class InitCmd final : public ISlashCommand {
public:
    // ---- Identity -----------------------------------------------------------

    [[nodiscard]] std::string_view name() const noexcept override {
        return "init";
    }

    [[nodiscard]] std::string_view description() const noexcept override {
        return "Scan the repo and write a starter BATBOX.md project-memory file.";
    }

    [[nodiscard]] std::string_view usage() const noexcept override {
        return "/init";
    }

    [[nodiscard]] std::vector<std::string> aliases() const override {
        return {};
    }

    [[nodiscard]] bool requires_args() const noexcept override { return false; }

    // ---- Execute ------------------------------------------------------------

    [[nodiscard]] batbox::Result<void> execute(
        std::string_view   /*args*/,
        CommandContext&    ctx) override;
};

// ---------------------------------------------------------------------------
// execute
// ---------------------------------------------------------------------------

batbox::Result<void> InitCmd::execute(
    std::string_view /*args*/,
    CommandContext&  ctx)
{
    const fs::path root      = ctx.cwd;
    const fs::path batbox_md = root / "BATBOX.md";

    // --- 1. Require at least one project marker ------------------------------

    bool has_marker = false;
    for (std::string_view marker : kMarkers) {
        if (fs::exists(root / marker)) {
            has_marker = true;
            break;
        }
    }

    if (!has_marker) {
        return batbox::Err(
            "/init: no project markers found in " + root.string() + ".\n"
            "Expected one of: package.json, Cargo.toml, CMakeLists.txt, "
            "pyproject.toml, go.mod, build.gradle, Makefile, or README."
        );
    }

    // --- 2. Ask before overwriting an existing BATBOX.md --------------------

    if (fs::exists(batbox_md)) {
        ctx.output
            << "BATBOX.md already exists in " << root.string() << ".\n"
            << "Overwrite it? [y/N] ";
        ctx.output.flush();

        std::string answer;
        if (!std::getline(ctx.input, answer)) {
            return batbox::Err(std::string("/init: cancelled (no input)."));
        }

        // Trim leading whitespace.
        const auto first_nws = answer.find_first_not_of(" \t\r\n");
        if (first_nws != std::string::npos) {
            answer = answer.substr(first_nws);
        }

        if (answer.empty() || (answer[0] != 'y' && answer[0] != 'Y')) {
            ctx.output << "/init: cancelled.\n";
            return {};
        }
    }

    // --- 3. Detect stack and scan tree ---------------------------------------

    const std::string stack = detect_stack(root);
    const std::string tree  = scan_tree(root);

    // --- 4. Write BATBOX.md --------------------------------------------------

    std::ofstream out_file(batbox_md, std::ios::out | std::ios::trunc);
    if (!out_file.is_open()) {
        return batbox::Err(
            "/init: could not open BATBOX.md for writing: " + batbox_md.string()
        );
    }

    out_file << make_batbox_md(root, stack, tree);
    out_file.close();

    ctx.output
        << "Wrote BATBOX.md to " << batbox_md.string() << '\n'
        << "Stack detected: " << stack << '\n'
        << "batbox will load this file as project context on each startup.\n";

    return {};
}

// ---------------------------------------------------------------------------
// Registration function
// ---------------------------------------------------------------------------

void register_init_cmd(SlashCommandRegistry& registry) {
    auto res = registry.register_command(std::make_shared<InitCmd>());
    (void)res;
}

} // namespace batbox::commands
