// src/commands/TerminalSetupCmd.cpp
//
// batbox::commands::TerminalSetupCmd — implements the /terminal-setup command.
//
// Probes the terminal environment and reports on:
//   • $TERM / $TERM_PROGRAM / $TERM_PROGRAM_VERSION identification
//   • Truecolor support ($COLORTERM == "truecolor" or "24bit")
//   • Italic text support (most modern terminals support VT100 italic)
//   • Mouse mode (reports whether TERM_PROGRAM suggests mouse-capable terminal)
//   • Kitty keyboard protocol detection ($KITTY_WINDOW_ID)
//   • Unicode support ($LANG / locale UTF-8 check)
//
// It then writes per-terminal configuration snippets to
//   ctx.config_dir / "terminal-snippets" / <terminal>.sh
// for the detected terminal (iTerm2, Alacritty, Kitty, WezTerm, others).
//
// Subcommands:
//   /terminal-setup            — probe + print + write snippet
//   /terminal-setup --dry-run  — probe + print only, do not write snippet
//
// No aliases.
//
// Registration entry point:
//   void register_terminal_setup_cmd(SlashCommandRegistry&);

#include <batbox/commands/ISlashCommand.hpp>
#include <batbox/commands/SlashCommandRegistry.hpp>
#include <batbox/core/Result.hpp>
#include <batbox/repl/CommandContext.hpp>

#include <cerrno>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;

namespace batbox::commands {

// ---------------------------------------------------------------------------
// Terminal capability detection helpers
// ---------------------------------------------------------------------------

namespace {

/// Safe wrapper around std::getenv — returns empty string_view when unset.
[[nodiscard]] std::string safe_getenv(const char* name) {
    const char* v = std::getenv(name);
    return (v && v[0] != '\0') ? std::string(v) : std::string{};
}

/// Detect the terminal emulator name from environment variables.
/// Returns one of: "iterm2", "kitty", "alacritty", "wezterm", "tmux",
///                 "vscode", "hyper", "xterm", "unknown"
[[nodiscard]] std::string detect_terminal() {
    const std::string prog = safe_getenv("TERM_PROGRAM");

    if (prog == "iTerm.app")                        return "iterm2";
    if (prog == "WezTerm")                          return "wezterm";
    if (prog == "vscode")                           return "vscode";
    if (prog == "Hyper")                            return "hyper";
    if (prog == "tmux")                             return "tmux";

    // Kitty sets KITTY_WINDOW_ID.
    if (!safe_getenv("KITTY_WINDOW_ID").empty())    return "kitty";

    // Alacritty sets ALACRITTY_LOG or ALACRITTY_SOCKET on newer versions.
    if (!safe_getenv("ALACRITTY_LOG").empty() ||
        !safe_getenv("ALACRITTY_SOCKET").empty())   return "alacritty";

    const std::string term = safe_getenv("TERM");
    if (term.find("xterm") != std::string::npos)    return "xterm";
    if (term.find("screen") != std::string::npos)   return "tmux";

    return "unknown";
}

/// True when the terminal claims 24-bit colour support.
[[nodiscard]] bool detect_truecolor() {
    const std::string colorterm = safe_getenv("COLORTERM");
    return (colorterm == "truecolor" || colorterm == "24bit");
}

/// Heuristic: does the locale / LANG suggest a UTF-8 capable terminal?
[[nodiscard]] bool detect_unicode() {
    const std::vector<const char*> vars = {"LC_ALL", "LC_CTYPE", "LANG"};
    for (const char* v : vars) {
        const std::string val = safe_getenv(v);
        if (val.find("UTF-8") != std::string::npos ||
            val.find("utf-8") != std::string::npos) {
            return true;
        }
    }
    return false;
}

/// True when Kitty keyboard protocol is likely supported.
[[nodiscard]] bool detect_kitty_protocol() {
    const std::string term = detect_terminal();
    return (term == "kitty" || term == "wezterm" || term == "iterm2");
}

/// Build a configuration snippet appropriate for the detected terminal.
[[nodiscard]] std::string build_snippet(const std::string& terminal,
                                        bool truecolor,
                                        bool unicode) {
    std::string s;
    s += "#!/bin/sh\n";
    s += "# batbox terminal-setup snippet — generated by /terminal-setup\n";
    s += "# Terminal: " + terminal + "\n";
    s += "#\n";
    s += "# Source this file from your shell rc (e.g. ~/.zshrc / ~/.bashrc):\n";
    s += "#   . ~/.batbox/terminal-snippets/" + terminal + ".sh\n";
    s += "#\n\n";

    if (terminal == "iterm2") {
        s += "# iTerm2 — enable truecolor and italic support\n";
        s += "export COLORTERM=truecolor\n";
        s += "# Use the xterm-256color-italic terminfo if installed:\n";
        s += "#   brew install ncurses && tic -xe xterm-256color-italic /path/to/xterm-256color-italic.terminfo\n";
        if (!truecolor) {
            s += "# HINT: Your $COLORTERM is not set; set it to 'truecolor' for best results.\n";
        }
        s += "# Mouse mode: enabled by iTerm2 by default; no extra setup needed.\n";
    } else if (terminal == "kitty") {
        s += "# Kitty — full feature support out of the box\n";
        s += "# Kitty uses its own terminfo; ensure 'kitty' terminfo is installed:\n";
        s += "#   kitty +kitten ssh myserver  # transfers terminfo automatically\n";
        s += "export COLORTERM=truecolor\n";
        s += "# Kitty keyboard protocol is enabled by default in kitty >= 0.23\n";
        s += "# For italic support, kitty handles it natively — no extra config needed.\n";
    } else if (terminal == "alacritty") {
        s += "# Alacritty — add to ~/.config/alacritty/alacritty.toml:\n";
        s += "# [terminal]\n";
        s += "# osc52 = \"CopyPaste\"  # for clipboard integration\n";
        s += "#\n";
        s += "# [colors]\n";
        s += "# # Alacritty supports truecolor natively; ensure COLORTERM is set:\n";
        s += "export COLORTERM=truecolor\n";
        s += "# For italic support in Alacritty, your font must have an italic variant.\n";
        s += "# Recommended: JetBrains Mono or Fira Code with italic.\n";
    } else if (terminal == "wezterm") {
        s += "# WezTerm — full feature support, similar to Kitty\n";
        s += "export COLORTERM=truecolor\n";
        s += "# WezTerm supports the Kitty keyboard protocol and italic natively.\n";
        s += "# Add to your ~/.wezterm.lua:\n";
        s += "#   config.enable_kitty_keyboard = true\n";
        s += "#   config.font = wezterm.font('JetBrains Mono', { italic = true })\n";
    } else if (terminal == "tmux") {
        s += "# tmux — ensure passthrough for truecolor and italic:\n";
        s += "# Add to ~/.tmux.conf:\n";
        s += "#   set -g default-terminal \"tmux-256color\"\n";
        s += "#   set -ag terminal-overrides \",xterm-256color:RGB\"\n";
        s += "#   set -as terminal-features \",xterm-256color:RGB\"\n";
        s += "export COLORTERM=truecolor\n";
        s += "# Italic passthrough in tmux requires: set -as terminal-overrides ',*:sitm=\\E[3m'\n";
    } else {
        // Generic / unknown
        s += "# Generic terminal setup\n";
        s += "export COLORTERM=truecolor\n";
        s += "# For italic support, your TERM must have an italic terminfo entry.\n";
        s += "# Common fix: export TERM=xterm-256color\n";
        if (!unicode) {
            s += "# HINT: Your locale does not appear to be UTF-8. Add to your rc:\n";
            s += "#   export LANG=en_US.UTF-8\n";
            s += "#   export LC_ALL=en_US.UTF-8\n";
        }
    }

    s += "\n# End of batbox terminal-setup snippet\n";
    return s;
}

/// Write the snippet file to config_dir/terminal-snippets/<terminal>.sh
/// Returns empty string on success, error description on failure.
[[nodiscard]] std::string write_snippet(const fs::path& config_dir,
                                        const std::string& terminal,
                                        const std::string& snippet) {
    const fs::path snippets_dir = config_dir / "terminal-snippets";
    std::error_code ec;
    fs::create_directories(snippets_dir, ec);
    if (ec) {
        return std::string("cannot create '") + snippets_dir.string()
               + "': " + ec.message();
    }

    const fs::path snippet_path = snippets_dir / (terminal + ".sh");
    std::ofstream f(snippet_path);
    if (!f) {
        return std::string("cannot write '") + snippet_path.string()
               + "': " + std::strerror(errno);
    }
    f << snippet;
    f.close();

    // Make executable.
    fs::permissions(snippet_path,
                    fs::perms::owner_read | fs::perms::owner_write | fs::perms::owner_exec |
                    fs::perms::group_read | fs::perms::others_read,
                    fs::perm_options::replace, ec);
    if (ec) {
        // Non-fatal: file is written; chmod failed.
        return {};
    }
    return {};
}

}  // namespace

// ---------------------------------------------------------------------------
// TerminalSetupCmd
// ---------------------------------------------------------------------------

class TerminalSetupCmd final : public ISlashCommand {
public:
    // ---- Identity -----------------------------------------------------------

    [[nodiscard]] std::string_view name() const noexcept override {
        return "terminal-setup";
    }

    [[nodiscard]] std::string_view description() const noexcept override {
        return "Detect terminal capabilities and write setup snippets.";
    }

    [[nodiscard]] std::string_view usage() const noexcept override {
        return "/terminal-setup [--dry-run]";
    }

    [[nodiscard]] std::vector<std::string> aliases() const override {
        return {};
    }

    [[nodiscard]] bool requires_args() const noexcept override { return false; }

    // ---- Execute ------------------------------------------------------------

    [[nodiscard]] batbox::Result<void> execute(
        std::string_view   args,
        CommandContext&    ctx) override;
};

// ---------------------------------------------------------------------------
// execute
// ---------------------------------------------------------------------------

batbox::Result<void> TerminalSetupCmd::execute(
    std::string_view args,
    CommandContext&  ctx)
{
    // Parse --dry-run flag.
    const auto start = args.find_first_not_of(" \t");
    const std::string_view sub = (start == std::string_view::npos)
        ? std::string_view{}
        : args.substr(start);
    const bool dry_run = (sub == "--dry-run");

    if (!sub.empty() && !dry_run) {
        return batbox::Err(
            std::string("/terminal-setup: unknown argument '") + std::string(sub)
            + "'. " + std::string(usage()));
    }

    // --- 1. Probe environment -----------------------------------------------

    const std::string terminal    = detect_terminal();
    const bool        truecolor   = detect_truecolor();
    const bool        unicode     = detect_unicode();
    const bool        kitty_proto = detect_kitty_protocol();
    const std::string term_var    = safe_getenv("TERM");
    const std::string term_prog   = safe_getenv("TERM_PROGRAM");
    const std::string term_ver    = safe_getenv("TERM_PROGRAM_VERSION");
    const std::string colorterm   = safe_getenv("COLORTERM");

    // --- 2. Print capabilities report ---------------------------------------

    ctx.output << "\n  Terminal capabilities\n";
    ctx.output << "  ─────────────────────────────────────────\n";
    ctx.output << "  Detected terminal  : " << terminal << "\n";
    ctx.output << "  $TERM              : " << (term_var.empty()  ? "(not set)" : term_var)  << "\n";
    ctx.output << "  $TERM_PROGRAM      : " << (term_prog.empty() ? "(not set)" : term_prog) << "\n";
    if (!term_ver.empty()) {
        ctx.output << "  $TERM_PROGRAM_VERSION : " << term_ver << "\n";
    }
    ctx.output << "  $COLORTERM         : " << (colorterm.empty() ? "(not set)" : colorterm) << "\n";
    ctx.output << "  ─────────────────────────────────────────\n";
    ctx.output << "  Truecolor (24-bit) : " << (truecolor   ? "YES" : "NO (recommend: export COLORTERM=truecolor)") << "\n";
    ctx.output << "  Italic support     : " << ((terminal == "kitty" || terminal == "wezterm" || terminal == "iterm2") ? "YES (terminal supports it)" : "LIKELY (depends on terminfo + font)") << "\n";
    ctx.output << "  Mouse mode         : " << ((terminal == "kitty" || terminal == "wezterm" || terminal == "iterm2" || terminal == "alacritty") ? "SUPPORTED" : "terminal-dependent") << "\n";
    ctx.output << "  Kitty kbd protocol : " << (kitty_proto ? "SUPPORTED" : "NOT DETECTED") << "\n";
    ctx.output << "  Unicode / UTF-8    : " << (unicode     ? "YES" : "NO (recommend: export LANG=en_US.UTF-8)") << "\n";
    ctx.output << "  ─────────────────────────────────────────\n\n";

    // --- 3. Write snippet (unless --dry-run) --------------------------------

    const std::string snippet = build_snippet(terminal, truecolor, unicode);
    const fs::path snippet_path = ctx.config_dir / "terminal-snippets" / (terminal + ".sh");

    if (dry_run) {
        ctx.output << "  --dry-run: snippet NOT written.\n";
        ctx.output << "  Would write to: " << snippet_path.string() << "\n\n";
        ctx.output << "  Snippet contents:\n";
        ctx.output << "  ─────────────────────────────────────────\n";
        // Indent each line of the snippet for display.
        std::istringstream ss(snippet);
        std::string line;
        while (std::getline(ss, line)) {
            ctx.output << "  " << line << "\n";
        }
        ctx.output << "  ─────────────────────────────────────────\n\n";
        return {};
    }

    const std::string write_err = write_snippet(ctx.config_dir, terminal, snippet);
    if (!write_err.empty()) {
        return batbox::Err("/terminal-setup: " + write_err);
    }

    ctx.output << "  Snippet written to: " << snippet_path.string() << "\n";
    ctx.output << "\n  To activate, add this to your ~/.zshrc or ~/.bashrc:\n";
    ctx.output << "    . " << snippet_path.string() << "\n\n";

    return {};
}

// ---------------------------------------------------------------------------
// Registration function
// ---------------------------------------------------------------------------

void register_terminal_setup_cmd(SlashCommandRegistry& registry) {
    auto res = registry.register_command(std::make_shared<TerminalSetupCmd>());
    (void)res;
}

} // namespace batbox::commands
