# =============================================================================
# src/skills/embed.cmake
# batbox_generate_skills_embed(<output_dir>)
#
# At CMake configure time, reads the 13 bundled skill .md files from
# ${PROJECT_SOURCE_DIR}/skills/bundled/ and generates:
#
#   <output_dir>/batbox/skills/skills_embed.inc
#
# The generated file defines a constexpr array of BundledSkillEntry structs
# (name + md_content char*).  BundledSkillsRegistry.cpp includes it.
#
# Embedding approach:
#   Each .md file is read with file(READ), then written into the .inc using
#   file(CONFIGURE OUTPUT ... CONTENT ... @ONLY) which performs ONLY @VAR@
#   substitution (not ${VAR} substitution), so dollar-brace sequences in
#   skill text are preserved verbatim in the output.  The content is embedded
#   as a C++ raw string literal with a per-entry delimiter BATSK_<INDEX> to
#   avoid conflicts with any text that might contain the word "BATSK_N".
#
# CMake re-generates the .inc whenever this .cmake file is re-included, i.e.,
# on every cmake re-run (configure step).  No custom_command overhead.
# =============================================================================

function(batbox_generate_skills_embed output_dir)

    # -------------------------------------------------------------------------
    # Canonical skill list — must match curated-surface.md exactly.
    # -------------------------------------------------------------------------
    set(_skill_names
        verify
        debug
        simplify
        batch
        update-config
        remember
        getshitdone
        stuck
        verify-content
        dream
        hunter
        loop
        schedule-remote-agents
    )

    # -------------------------------------------------------------------------
    # Ensure the output directory exists.
    # -------------------------------------------------------------------------
    file(MAKE_DIRECTORY "${output_dir}/batbox/skills")

    set(_inc_path "${output_dir}/batbox/skills/skills_embed.inc")

    # -------------------------------------------------------------------------
    # Write the file header.
    # file(CONFIGURE @ONLY) is used throughout so that ${VAR} patterns inside
    # skill content are NOT treated as CMake variables.
    # -------------------------------------------------------------------------
    set(_header_content
"// AUTO-GENERATED by src/skills/embed.cmake — do not edit by hand.\n\
// Re-generated at CMake configure time from skills/bundled/*.md.\n\
// Included by src/skills/BundledSkillsRegistry.cpp.\n\
\n\
namespace {\n\
\n\
/// One embedded bundled skill: canonical name + raw .md content.\n\
struct BundledSkillEntry {\n\
    const char* name;        ///< Skill name key\n\
    const char* md_content;  ///< Full .md text including YAML frontmatter\n\
};\n\
\n\
/// All 13 bundled skills in canonical order (curated-surface.md).\n\
constexpr BundledSkillEntry k_bundled_skills[] = {\n")

    file(CONFIGURE
        OUTPUT  "${_inc_path}"
        CONTENT "${_header_content}"
        @ONLY)

    # -------------------------------------------------------------------------
    # Append one entry per skill.
    # -------------------------------------------------------------------------
    set(_index 0)
    foreach(_name IN LISTS _skill_names)
        set(_md_path "${PROJECT_SOURCE_DIR}/skills/bundled/${_name}.md")

        if(NOT EXISTS "${_md_path}")
            message(FATAL_ERROR
                "batbox_generate_skills_embed: missing bundled skill file:\n"
                "  ${_md_path}\n"
                "All 13 bundled skill .md files must exist before configuring.")
        endif()

        # Read the .md content verbatim into a CMake variable.
        file(READ "${_md_path}" _md_content)

        # Use a per-entry raw string delimiter (BATSK_<index>) to guarantee no
        # conflict with skill content.  The delimiter is a pure ASCII identifier
        # unlikely to appear in any natural-language prompt body.
        set(_delim "BATSK_${_index}")

        # Build the entry string.  We use @_name@, @_delim@, and @_md_content@
        # as @VAR@ substitution tokens so that file(CONFIGURE @ONLY) handles
        # the expansion and ${...} sequences in skill text are left alone.
        set(_entry_template "    { \"@_name@\", R\"@_delim@(@_md_content@)@_delim@\" },\n")

        file(CONFIGURE
            OUTPUT  "${_inc_path}.entry_tmp"
            CONTENT "${_entry_template}"
            @ONLY)

        # Read the expanded entry back and append it to the .inc.
        file(READ "${_inc_path}.entry_tmp" _expanded_entry)
        file(APPEND "${_inc_path}" "${_expanded_entry}")

        math(EXPR _index "${_index} + 1")
    endforeach()

    # Clean up the temporary entry file.
    file(REMOVE "${_inc_path}.entry_tmp")

    # -------------------------------------------------------------------------
    # Close the array and namespace.
    # -------------------------------------------------------------------------
    file(APPEND "${_inc_path}"
"};\n\n} // anonymous namespace\n")

    message(STATUS "  batbox_skills: generated ${_inc_path} (${_index} skills)")

endfunction()
