# cmake/Theme.cmake
# ---------------------------------------------------------------------------
# batbox_generate_themes_header(<output_dir>)
#
# Reads data/themes.json at CMake configure time and writes:
#   <output_dir>/batbox/themes/Themes.hpp
#
# The generated header is C++20:
#   - struct BatboxColor  { uint8_t r, g, b; }
#   - struct BatboxTheme  { std::string_view name; BatboxColor background; ... }
#   - constexpr std::array<BatboxTheme, N> kThemes   (indexed by theme name)
#   - constexpr std::string_view kDefaultThemeName   ("miss-kittin")
#
# Re-runs if data/themes.json changes: the function stamps a configure_file
# dependency so CMake picks up the invalidation automatically.
#
# Typical call (from top-level CMakeLists.txt once the TUI target exists):
#   batbox_generate_themes_header("${CMAKE_BINARY_DIR}/generated/include")
#
# The generated include path is then added to the TUI target:
#   target_include_directories(batbox_tui PRIVATE
#       "${CMAKE_BINARY_DIR}/generated/include")
# ---------------------------------------------------------------------------

cmake_minimum_required(VERSION 3.24)

# ---------------------------------------------------------------------------
# Internal helper: write the Python generator script to the build tree once.
# We embed it here so Theme.cmake is the single source of truth — no extra
# files to track.
# ---------------------------------------------------------------------------
function(_batbox_write_theme_generator script_path)
    file(WRITE "${script_path}" [==[
#!/usr/bin/env python3
"""
batbox theme header generator — invoked by cmake/Theme.cmake at configure time.
Reads data/themes.json, writes batbox/themes/Themes.hpp.
"""
import json
import sys
import os
import textwrap
from datetime import datetime, timezone

def hex_to_rgb(hex_str: str) -> tuple[int, int, int]:
    """Convert '#rrggbb' to (r, g, b) integers."""
    h = hex_str.lstrip('#')
    if len(h) != 6:
        raise ValueError(f"Expected 6-char hex colour, got: '{hex_str}'")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

def escape_str(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')

def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <themes.json> <output_dir>", file=sys.stderr)
        return 1

    json_path = sys.argv[1]
    out_dir   = sys.argv[2]

    with open(json_path, encoding='utf-8') as f:
        data = json.load(f)

    themes = data['themes']
    if not themes:
        print("ERROR: themes array is empty", file=sys.stderr)
        return 1

    # Scalar colour fields (order matters — must match struct member order below)
    SCALAR_FIELDS = [
        'background', 'foreground', 'dim',
        'accent', 'accent2',
        'danger', 'success', 'warning', 'info',
        'demon_panel', 'status_bar',
    ]

    # Validate every theme has required fields
    required = set(SCALAR_FIELDS) | {'name', 'display_name', 'description', 'ansi16'}
    for t in themes:
        missing = required - set(t.keys())
        if missing:
            print(f"ERROR: theme '{t.get('name','?')}' missing fields: {missing}", file=sys.stderr)
            return 1
        if len(t['ansi16']) != 16:
            print(f"ERROR: theme '{t['name']}' ansi16 must have exactly 16 entries", file=sys.stderr)
            return 1

    default_name = themes[0]['name']  # first theme = default
    n = len(themes)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

    lines = []
    lines.append(f'// AUTO-GENERATED by cmake/Theme.cmake — DO NOT EDIT BY HAND')
    lines.append(f'// Source: data/themes.json  |  Generated: {now}')
    lines.append(f'//')
    lines.append(f'// To change themes, edit data/themes.json and re-run CMake.')
    lines.append('')
    lines.append('#pragma once')
    lines.append('')
    lines.append('#include <array>')
    lines.append('#include <cstdint>')
    lines.append('#include <string_view>')
    lines.append('')
    lines.append('namespace batbox::themes {')
    lines.append('')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('// Primitive colour type — 24-bit RGB, compatible with FTXUI Color::RGB().')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('struct BatboxColor {')
    lines.append('    uint8_t r{};')
    lines.append('    uint8_t g{};')
    lines.append('    uint8_t b{};')
    lines.append('')
    lines.append('    // Returns true if the colour is pure black (unset sentinel).')
    lines.append('    [[nodiscard]] constexpr bool is_black() const noexcept {')
    lines.append('        return r == 0 && g == 0 && b == 0;')
    lines.append('    }')
    lines.append('};')
    lines.append('')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('// Full theme descriptor.')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('struct BatboxTheme {')
    lines.append('    std::string_view name;')
    lines.append('    std::string_view display_name;')
    lines.append('    std::string_view description;')
    lines.append('')
    lines.append('    // Semantic colour roles')
    lines.append('    BatboxColor background;')
    lines.append('    BatboxColor foreground;')
    lines.append('    BatboxColor dim;')
    lines.append('    BatboxColor accent;')
    lines.append('    BatboxColor accent2;')
    lines.append('    BatboxColor danger;')
    lines.append('    BatboxColor success;')
    lines.append('    BatboxColor warning;')
    lines.append('    BatboxColor info;')
    lines.append('    BatboxColor demon_panel;')
    lines.append('    BatboxColor status_bar;')
    lines.append('')
    lines.append('    // 16-colour ANSI palette override (indices 0-15)')
    lines.append('    std::array<BatboxColor, 16> ansi16;')
    lines.append('};')
    lines.append('')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('// Compile-time theme table — all themes, indexed 0..N-1.')
    lines.append('// Use theme_by_name() for name-based lookup.')
    lines.append('// ---------------------------------------------------------------------------')

    def color_lit(hex_str: str) -> str:
        r, g, b = hex_to_rgb(hex_str)
        return f'BatboxColor{{{r}u, {g}u, {b}u}}'

    def ansi16_lit(entries: list) -> str:
        inner = ', '.join(color_lit(e) for e in entries)
        return f'std::array<BatboxColor, 16>{{{{{inner}}}}}'

    lines.append(f'inline constexpr std::array<BatboxTheme, {n}> kThemes = {{{{')
    for idx, t in enumerate(themes):
        comma = '' if idx == n - 1 else ','
        lines.append(f'    // [{idx}] {t["name"]}')
        lines.append(f'    BatboxTheme{{')
        lines.append(f'        .name         = "{escape_str(t["name"])}",')
        lines.append(f'        .display_name = "{escape_str(t["display_name"])}",')
        lines.append(f'        .description  = "{escape_str(t["description"])}",')
        for field in SCALAR_FIELDS:
            lines.append(f'        .{field:<11} = {color_lit(t[field])},')
        lines.append(f'        .ansi16       = {ansi16_lit(t["ansi16"])},')
        lines.append(f'    }}{comma}')

    lines.append(f'}}}};')
    lines.append('')
    lines.append(f'inline constexpr std::string_view kDefaultThemeName = "{escape_str(default_name)}";')
    lines.append(f'inline constexpr std::size_t      kThemeCount        = {n};')
    lines.append('')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('// theme_by_name — O(N) linear scan; N is small (5 themes).')
    lines.append('// Returns nullptr if name is not found.')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('[[nodiscard]] constexpr const BatboxTheme*')
    lines.append('theme_by_name(std::string_view name) noexcept {')
    lines.append('    for (const auto& t : kThemes) {')
    lines.append('        if (t.name == name) { return &t; }')
    lines.append('    }')
    lines.append('    return nullptr;')
    lines.append('}')
    lines.append('')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('// default_theme — convenience accessor.')
    lines.append('// ---------------------------------------------------------------------------')
    lines.append('[[nodiscard]] constexpr const BatboxTheme& default_theme() noexcept {')
    lines.append('    return kThemes[0];')
    lines.append('}')
    lines.append('')
    lines.append('} // namespace batbox::themes')
    lines.append('')

    out_file = os.path.join(out_dir, 'batbox', 'themes', 'Themes.hpp')
    os.makedirs(os.path.dirname(out_file), exist_ok=True)

    content = '\n'.join(lines)
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"[batbox/themes] Generated {out_file} ({len(themes)} themes)")
    return 0

if __name__ == '__main__':
    sys.exit(main())
]==])
endfunction()

# ---------------------------------------------------------------------------
# batbox_generate_themes_header(<output_dir>)
#
# <output_dir> — directory under which batbox/themes/Themes.hpp is written.
#                Typically ${CMAKE_BINARY_DIR}/generated/include.
# ---------------------------------------------------------------------------
function(batbox_generate_themes_header output_dir)
    # ------------------------------------------------------------------
    # Locate Python 3 (required for the generator script).
    # ------------------------------------------------------------------
    find_package(Python3 REQUIRED COMPONENTS Interpreter)

    # ------------------------------------------------------------------
    # Resolve the source JSON path relative to the project root.
    # ------------------------------------------------------------------
    set(_themes_json "${CMAKE_SOURCE_DIR}/data/themes.json")

    if(NOT EXISTS "${_themes_json}")
        message(FATAL_ERROR
            "[batbox/themes] data/themes.json not found at '${_themes_json}'.\n"
            "  Create the file first (see cmake/Theme.cmake for the expected schema).")
    endif()

    # ------------------------------------------------------------------
    # Write the embedded Python generator into the build tree.
    # We write it on every configure pass but CMake's file(WRITE) is
    # a no-op when the content hasn't changed, so this is cheap.
    # ------------------------------------------------------------------
    set(_generator_script "${CMAKE_BINARY_DIR}/batbox_theme_generator.py")
    _batbox_write_theme_generator("${_generator_script}")

    # ------------------------------------------------------------------
    # Run the generator NOW (configure time) so the header is available
    # before any C++ compilation begins.
    # ------------------------------------------------------------------
    set(_out_hpp "${output_dir}/batbox/themes/Themes.hpp")

    execute_process(
        COMMAND "${Python3_EXECUTABLE}" "${_generator_script}"
                "${_themes_json}"
                "${output_dir}"
        RESULT_VARIABLE _gen_result
        OUTPUT_VARIABLE _gen_stdout
        ERROR_VARIABLE  _gen_stderr
    )

    if(NOT _gen_result EQUAL 0)
        message(FATAL_ERROR
            "[batbox/themes] Header generation failed (exit ${_gen_result}).\n"
            "stdout: ${_gen_stdout}\n"
            "stderr: ${_gen_stderr}")
    endif()

    if(_gen_stdout)
        message(STATUS "${_gen_stdout}")
    endif()

    # ------------------------------------------------------------------
    # configure_file dependency: CMake re-configures when themes.json
    # changes because configure_file records a dependency on its input.
    # We use COPYONLY into the build tree; the copy itself is not used,
    # but the dependency tracking is the whole point.
    # ------------------------------------------------------------------
    configure_file(
        "${_themes_json}"
        "${CMAKE_BINARY_DIR}/batbox_themes_json.stamp"
        COPYONLY
    )

    # ------------------------------------------------------------------
    # Expose the output directory via a cache variable so callers can
    # easily wire it into target_include_directories().
    # ------------------------------------------------------------------
    set(BATBOX_THEMES_INCLUDE_DIR "${output_dir}"
        CACHE PATH
        "Directory containing the generated batbox/themes/Themes.hpp header"
        FORCE
    )

    message(STATUS "[batbox/themes] Header ready: ${_out_hpp}")
    message(STATUS "[batbox/themes] Add to target: target_include_directories(<target> PRIVATE \${BATBOX_THEMES_INCLUDE_DIR})")
endfunction()
