// tests/unit/test_context_window_estimator.cpp — doctest suite for CPP 3.2
//
// Tests the batbox::conversation::ContextWindow token estimator against
// tiktoken 0.13.0 reference counts.
//
// Coverage:
//   1.  Context-limit lookup: known models return correct limits
//   2.  Context-limit lookup: unknown model returns 128 000 default
//   3.  uses_o200k: o1-preview, o1-mini, o1 use o200k; gpt-4o does not
//   4.  estimate_string: empty string -> 0 tokens
//   5.  estimate_string: ASCII-only strings match reference within 5% (per string)
//   6.  estimate_string: CJK text uses cl100k rate correctly
//   7.  estimate_string: o200k CJK rate gives fewer tokens than cl100k
//   8.  estimate_string: emoji tokenization (cl100k vs o200k differ)
//   9.  estimate_string: mixed unicode / emoji / CJK
//   10. estimate_tokens: conversation overhead (3 prefix + 4 per message)
//   11. estimate_tokens: empty conversation returns 3 (prefix only)
//   12. needs_compact: below threshold returns false
//   13. needs_compact: at threshold returns true
//   14. needs_compact: above threshold returns true
//   15. set_model_context_limit: updates limit, needs_compact reflects it
//   16. set_model: switching to o1-preview changes table and limit
//   17. set_model: switching back to gpt-4o restores cl100k and 128k limit
//   18. Corpus-level accuracy: sum of 19 reference estimates within 5% of 356
//   19. Corpus-level accuracy: o200k corpus sum within 5% of 344
//   20. ContextWindow constructor reads config fields correctly
//
// Build standalone (no CMake, from repo root):
//   c++ -std=c++20 \
//       -I include \
//       -I build/vcpkg_installed/arm64-osx/include \
//       tests/unit/test_context_window_estimator.cpp \
//       src/conversation/ContextWindow.cpp \
//       src/conversation/Message.cpp \
//       src/core/Uuid.cpp \
//       build/vcpkg_installed/arm64-osx/lib/libsimdjson.a \
//       -o /tmp/test_cw && /tmp/test_cw

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

#include <batbox/conversation/ContextWindow.hpp>
#include <batbox/conversation/Message.hpp>
#include <batbox/config/Config.hpp>

#include <cmath>
#include <string>
#include <vector>

using namespace batbox::conversation;
using batbox::config::Config;

// =============================================================================
// Reference token counts generated by tiktoken 0.13.0
// Format: { description, text, cl100k_actual, o200k_actual }
// =============================================================================

namespace {

struct RefCase {
    const char* description;
    const char* text;
    int         cl100k;
    int         o200k;
};

// Generated by: python3 -c "import tiktoken; enc=tiktoken.get_encoding('cl100k_base'); ..."
// Corpus cl100k total: 356
// Corpus o200k  total: 344
static const RefCase kRefCases[] = {
    // Pure ASCII cases
    { "single word",
      "Hello",
      1, 1 },
    { "simple greeting",
      "Hello, world!",
      4, 4 },
    { "prose sentence",
      "The quick brown fox jumps over the lazy dog.",
      10, 10 },
    { "python code",
      "def fibonacci(n):\n    return n if n <= 1 else fibonacci(n-1) + fibonacci(n-2)",
      24, 24 },
    { "json object",
      "{\"key\": \"value\", \"num\": 42, \"arr\": [1, 2, 3]}",
      24, 24 },
    { "sql query",
      "SELECT * FROM users WHERE active = true ORDER BY created_at DESC LIMIT 100;",
      17, 17 },
    // Unicode cases
    { "emoji sequence",
      "\U0001F600\U0001F64F\U0001F680\U0001F4BB\U0001F525",
      13, 7 },
    { "cjk text",
      "你好世界，这是一个测试字符串",
      11, 6 },
    { "mixed content",
      "Hello \U0001F44B, 你好! Code: x = 42",
      14, 13 },
    // Code + punctuation dense
    { "multiline cpp code",
      "#include <iostream>\nint main() {\n    std::cout << \"Hello\" << std::endl;\n    return 0;\n}",
      27, 27 },
    { "long prose",
      "In the beginning, software was simple. Programs fit on punch cards, and entire "
      "operating systems were measured in kilobytes. Today we have gigabytes of RAM and "
      "terabytes of storage, yet somehow our applications feel slower than ever. "
      "Perhaps we have forgotten the lessons of the past.",
      57, 57 },
    { "repeated word",
      "test test test test test test test test test test test test test test test test test test test test ",
      21, 21 },
    { "numbers",
      "12345678901234567890",
      7, 7 },
    { "punctuation heavy",
      "!@#$%^&*()_+-=[]{}|;':\",./<>?",
      18, 18 },
    { "newlines",
      "line 0\nline 1\nline 2\nline 3\nline 4\nline 5\nline 6\nline 7\nline 8\nline 9",
      39, 39 },
    { "url",
      "https://www.example.com/api/v1/users?page=1&limit=100&sort=name",
      19, 19 },
    { "markdown",
      "# Title\n## Subtitle\n- item one\n- item two\n**bold** and *italic*",
      22, 21 },
    { "error message",
      "Error: ENOENT: no such file or directory, open '/home/user/project/config.json'",
      20, 20 },
    { "camelCase identifier",
      "thisIsACamelCaseIdentifierWithManyWords",
      8, 9 },
};

static constexpr int kRefCasesCount       = static_cast<int>(sizeof(kRefCases) / sizeof(kRefCases[0]));
static constexpr int kCorpusTotalCl100k   = 356;
static constexpr int kCorpusTotalO200k    = 344;
static constexpr double kCorpusTolerance  = 0.05; // 5%

// Helper: build a minimal valid Config with a specific model
Config make_config(const char* model, int compact_pct = 80) {
    Config cfg = Config::load_default();
    cfg.api.default_model        = model;
    cfg.compact.auto_compact_at_pct = compact_pct;
    return cfg;
}

// Helper: build a Message with the given role and content
Message make_msg(const std::string& content, Role role = Role::User) {
    Message m;
    m.role    = role;
    m.content = content;
    return m;
}

} // anonymous namespace

// =============================================================================
// 1. Context-limit lookup: known models
// =============================================================================

TEST_CASE("context_limit_for_model: known models return correct limits") {
    CHECK(ContextWindow::context_limit_for_model("gpt-4o")         == 128'000u);
    CHECK(ContextWindow::context_limit_for_model("gpt-4o-mini")    == 128'000u);
    CHECK(ContextWindow::context_limit_for_model("gpt-4-turbo")    == 128'000u);
    CHECK(ContextWindow::context_limit_for_model("gpt-4")          ==   8'192u);
    CHECK(ContextWindow::context_limit_for_model("gpt-3.5-turbo")  ==  16'385u);
    CHECK(ContextWindow::context_limit_for_model("o1-preview")     == 128'000u);
    CHECK(ContextWindow::context_limit_for_model("o1-mini")        == 128'000u);
    CHECK(ContextWindow::context_limit_for_model("o1")             == 200'000u);
    CHECK(ContextWindow::context_limit_for_model("o1-pro")         == 200'000u);
    CHECK(ContextWindow::context_limit_for_model("o3-mini")        == 200'000u);
}

// =============================================================================
// 2. Context-limit lookup: unknown model returns default
// =============================================================================

TEST_CASE("context_limit_for_model: unknown model returns 128000") {
    CHECK(ContextWindow::context_limit_for_model("unknown-model-xyz") == 128'000u);
    CHECK(ContextWindow::context_limit_for_model("")                   == 128'000u);
    CHECK(ContextWindow::context_limit_for_model("llama-3-70b")       == 128'000u);
}

// =============================================================================
// 3. uses_o200k: correct model family detection
// =============================================================================

TEST_CASE("uses_o200k: o1 and o3 families return true; others return false") {
    CHECK(ContextWindow::uses_o200k("o1-preview") == true);
    CHECK(ContextWindow::uses_o200k("o1-mini")    == true);
    CHECK(ContextWindow::uses_o200k("o1")         == true);
    CHECK(ContextWindow::uses_o200k("o1-pro")     == true);
    CHECK(ContextWindow::uses_o200k("o3-mini")    == true);
    CHECK(ContextWindow::uses_o200k("o3")         == true);

    CHECK(ContextWindow::uses_o200k("gpt-4o")        == false);
    CHECK(ContextWindow::uses_o200k("gpt-4o-mini")   == false);
    CHECK(ContextWindow::uses_o200k("gpt-4-turbo")   == false);
    CHECK(ContextWindow::uses_o200k("gpt-4")         == false);
    CHECK(ContextWindow::uses_o200k("gpt-3.5-turbo") == false);
    CHECK(ContextWindow::uses_o200k("")              == false);
}

// =============================================================================
// 4. estimate_string: empty string returns 0
// =============================================================================

TEST_CASE("estimate_string: empty string returns 0 for both tables") {
    CHECK(ContextWindow::estimate_string("", false) == 0u);
    CHECK(ContextWindow::estimate_string("", true)  == 0u);
}

// =============================================================================
// 5. estimate_string: ASCII-only strings — reference corpus per-case check
// =============================================================================

TEST_CASE("estimate_string cl100k: ASCII cases match reference within 10x tolerance") {
    // We verify that estimates are in the right order of magnitude.
    // Corpus-level 5% accuracy is verified in test 18.
    for (int i = 0; i < kRefCasesCount; ++i) {
        const auto& rc = kRefCases[i];
        if (rc.cl100k == 0) continue;  // skip empty

        const int est = static_cast<int>(ContextWindow::estimate_string(rc.text, false));
        // Each estimate must be at least 1 and at most 5x the actual
        // (wide tolerance; corpus-level tightening is done separately)
        INFO("Case: " << rc.description);
        CHECK(est >= 1);
        CHECK(est <= rc.cl100k * 5 + 5);
    }
}

// =============================================================================
// 6. estimate_string: CJK — cl100k gives more tokens than chars
// =============================================================================

TEST_CASE("estimate_string cl100k: CJK text estimates approximately 1 token per char") {
    // "你好世界" = 4 CJK chars, actual cl100k = 4 tokens
    const std::size_t est = ContextWindow::estimate_string("你好世界", false);
    // Allow 50% relative error on 4 tokens: est must be in [2, 6]
    CHECK(est >= 2u);
    CHECK(est <= 6u);
}

// =============================================================================
// 7. estimate_string: CJK — o200k gives fewer tokens than cl100k
// =============================================================================

TEST_CASE("estimate_string: o200k CJK estimate is lower than cl100k") {
    // For CJK text, o200k is more efficient (larger vocabulary covers more kanji)
    const std::size_t est_cl = ContextWindow::estimate_string("你好世界，这是一个测试字符串", false);
    const std::size_t est_o2 = ContextWindow::estimate_string("你好世界，这是一个测试字符串", true);
    CHECK(est_o2 < est_cl);  // o200k should estimate fewer tokens for CJK
}

// =============================================================================
// 8. estimate_string: emoji — cl100k and o200k differ as expected
// =============================================================================

TEST_CASE("estimate_string: emoji sequence differs between cl100k and o200k") {
    // 5 emoji: cl100k_actual=13, o200k_actual=7
    // cl100k uses fewer chars per token for emoji (more tokens per emoji)
    const std::string five_emoji = "\U0001F600\U0001F64F\U0001F680\U0001F4BB\U0001F525";
    const std::size_t est_cl = ContextWindow::estimate_string(five_emoji, false);
    const std::size_t est_o2 = ContextWindow::estimate_string(five_emoji, true);
    // cl100k should estimate more tokens than o200k for emoji
    CHECK(est_cl > est_o2);
    // Both should be non-zero
    CHECK(est_cl >= 1u);
    CHECK(est_o2 >= 1u);
}

// =============================================================================
// 9. estimate_string: mixed unicode / emoji / CJK / ASCII
// =============================================================================

TEST_CASE("estimate_string: mixed unicode content returns a sane non-zero estimate") {
    // "Hello 👋, 你好! Code: x = 42"  actual: cl100k=14, o200k=13
    const std::string mixed = "Hello \U0001F44B, 你好! Code: x = 42";
    const std::size_t est_cl = ContextWindow::estimate_string(mixed, false);
    const std::size_t est_o2 = ContextWindow::estimate_string(mixed, true);
    CHECK(est_cl >= 5u);
    CHECK(est_cl <= 30u);
    CHECK(est_o2 >= 5u);
    CHECK(est_o2 <= 30u);
}

// =============================================================================
// 10. estimate_tokens: conversation overhead (3 prefix + 4 per message)
// =============================================================================

TEST_CASE("estimate_tokens: accounts for 3 prefix + 4 per-message overhead") {
    Config cfg = make_config("gpt-4o");
    ContextWindow cw(cfg);

    // One message with empty content:
    // total = 3 (prefix) + 4 (per-message overhead) + 0 (empty content) = 7
    {
        std::vector<Message> msgs = { make_msg("") };
        const std::size_t est = cw.estimate_tokens(msgs);
        CHECK(est == 7u);
    }

    // Two messages with empty content:
    // total = 3 + 4 + 0 + 4 + 0 = 11
    {
        std::vector<Message> msgs = { make_msg(""), make_msg("") };
        const std::size_t est = cw.estimate_tokens(msgs);
        CHECK(est == 11u);
    }
}

// =============================================================================
// 11. estimate_tokens: empty conversation returns 3 (prefix only)
// =============================================================================

TEST_CASE("estimate_tokens: empty messages vector returns 3 (prefix overhead)") {
    Config cfg = make_config("gpt-4o");
    ContextWindow cw(cfg);
    std::vector<Message> empty;
    CHECK(cw.estimate_tokens(empty) == 3u);
}

// =============================================================================
// 12. needs_compact: below threshold returns false
// =============================================================================

TEST_CASE("needs_compact: returns false when estimated tokens < threshold") {
    // Config: 80% of 128k = 102400 threshold
    Config cfg = make_config("gpt-4o", 80);
    ContextWindow cw(cfg);

    CHECK_FALSE(cw.needs_compact(0));
    CHECK_FALSE(cw.needs_compact(50'000));
    CHECK_FALSE(cw.needs_compact(102'399));
}

// =============================================================================
// 13. needs_compact: at threshold returns true
// =============================================================================

TEST_CASE("needs_compact: returns true when estimated tokens == threshold") {
    // 80% of 128000 = 102400
    Config cfg = make_config("gpt-4o", 80);
    ContextWindow cw(cfg);
    CHECK(cw.needs_compact(102'400));
}

// =============================================================================
// 14. needs_compact: above threshold returns true
// =============================================================================

TEST_CASE("needs_compact: returns true when estimated tokens > threshold") {
    Config cfg = make_config("gpt-4o", 80);
    ContextWindow cw(cfg);
    CHECK(cw.needs_compact(102'401));
    CHECK(cw.needs_compact(128'000));
    CHECK(cw.needs_compact(200'000));
}

// =============================================================================
// 15. set_model_context_limit: updates limit, needs_compact reflects new limit
// =============================================================================

TEST_CASE("set_model_context_limit: updates context limit; needs_compact uses new value") {
    Config cfg = make_config("gpt-4o", 80);
    ContextWindow cw(cfg);
    REQUIRE(cw.model_context_limit() == 128'000u);

    // Change to 8192 (gpt-4 base)
    cw.set_model_context_limit(8'192);
    CHECK(cw.model_context_limit() == 8'192u);

    // 80% of 8192 = 6553
    CHECK_FALSE(cw.needs_compact(6'552));
    CHECK(cw.needs_compact(6'553));
}

// =============================================================================
// 16. set_model: switching to o1-preview changes table and limit
// =============================================================================

TEST_CASE("set_model: switching to o1-preview updates is_o200k and context limit") {
    Config cfg = make_config("gpt-4o", 80);
    ContextWindow cw(cfg);
    REQUIRE(cw.model_context_limit() == 128'000u);

    cw.set_model("o1-preview");
    CHECK(cw.model_context_limit() == 128'000u);

    // After switching to o1-preview, CJK should give fewer tokens (o200k rates)
    // Verify by comparing estimates for a CJK-heavy string
    const std::string cjk_str = "你好世界，这是一个测试";

    // Create a CJK-only message and compare
    {
        std::vector<Message> msgs = { make_msg(cjk_str) };
        const std::size_t est_after_o1 = cw.estimate_tokens(msgs);

        // Reset to gpt-4o and compare
        cw.set_model("gpt-4o");
        const std::size_t est_gpt4o = cw.estimate_tokens(msgs);

        // o200k (o1) should give a smaller estimate for CJK
        CHECK(est_after_o1 <= est_gpt4o);
    }
}

// =============================================================================
// 17. set_model: switching back to gpt-4o restores cl100k and 128k limit
// =============================================================================

TEST_CASE("set_model: round-trip through o1 and back to gpt-4o restores state") {
    Config cfg = make_config("gpt-4o", 80);
    ContextWindow cw(cfg);

    const std::size_t limit_before = cw.model_context_limit();
    cw.set_model("o1-mini");
    cw.set_model("gpt-4o");

    CHECK(cw.model_context_limit() == limit_before);
}

// =============================================================================
// 18. Corpus-level accuracy: cl100k total within 5% of 356
// =============================================================================

TEST_CASE("corpus accuracy: cl100k sum is within 5% of tiktoken reference total (356)") {
    int estimated_total = 0;
    for (int i = 0; i < kRefCasesCount; ++i) {
        estimated_total += static_cast<int>(
            ContextWindow::estimate_string(kRefCases[i].text, false));
    }

    const double error_pct = std::abs(estimated_total - kCorpusTotalCl100k)
                           / static_cast<double>(kCorpusTotalCl100k);

    INFO("Estimated total: " << estimated_total
         << ", Reference: " << kCorpusTotalCl100k
         << ", Error: " << (error_pct * 100.0) << "%");

    CHECK(error_pct <= kCorpusTolerance);
}

// =============================================================================
// 19. Corpus-level accuracy: o200k total within 5% of 344
// =============================================================================

TEST_CASE("corpus accuracy: o200k sum is within 5% of tiktoken reference total (344)") {
    int estimated_total = 0;
    for (int i = 0; i < kRefCasesCount; ++i) {
        estimated_total += static_cast<int>(
            ContextWindow::estimate_string(kRefCases[i].text, true));
    }

    const double error_pct = std::abs(estimated_total - kCorpusTotalO200k)
                           / static_cast<double>(kCorpusTotalO200k);

    INFO("Estimated total: " << estimated_total
         << ", Reference: " << kCorpusTotalO200k
         << ", Error: " << (error_pct * 100.0) << "%");

    CHECK(error_pct <= kCorpusTolerance);
}

// =============================================================================
// 20. ContextWindow constructor reads config fields correctly
// =============================================================================

TEST_CASE("ContextWindow constructor: reads auto_compact_at_pct from config") {
    {
        Config cfg = make_config("gpt-4o", 90);
        ContextWindow cw(cfg);
        CHECK(cw.auto_compact_at_pct() == 90);
    }
    {
        Config cfg = make_config("gpt-4o", 50);
        ContextWindow cw(cfg);
        CHECK(cw.auto_compact_at_pct() == 50);
        // 50% of 128k = 64000
        CHECK_FALSE(cw.needs_compact(63'999));
        CHECK(cw.needs_compact(64'000));
    }
}

TEST_CASE("ContextWindow constructor: reads model from config for context limit") {
    {
        Config cfg = make_config("gpt-4", 80);
        ContextWindow cw(cfg);
        CHECK(cw.model_context_limit() == 8'192u);
    }
    {
        Config cfg = make_config("gpt-3.5-turbo", 80);
        ContextWindow cw(cfg);
        CHECK(cw.model_context_limit() == 16'385u);
    }
    {
        Config cfg = make_config("o1-mini", 80);
        ContextWindow cw(cfg);
        CHECK(cw.model_context_limit() == 128'000u);
    }
}
